query CinemasNearCity ($search: String!, $location: String, $distance: Int = 25) {
  cinemas (search: $search, location: $location, distance: $distance) {
    id
    name
    street
    city {
      name
    }
    distance
    detailUrl {
      url
    }
  }
}
