query {
  cinemas (search: "Open Air", location: "München", distance: 25, limit: 10) {
    id
    name
    street
    city {
      name
    }
    distance
    detailUrl {
      absoluteUrl
    }
  }
}
