query SearchMovies ($search: String! = "Avenger") {
  movies (search: $search) {
    title
    description
    additionalDescription
    genres {
      name
    }
    detailUrl {
      absoluteUrl
    }
    thumb {
      url {
        absoluteUrl
      }
    }
  }
}
