query GetShowsForDate ($cinemaId: ID!, $date: String! = "2018-09-18") {
  shows (cinemaId: $cinemaId, date: $date) {
    name
    beginning {
      formatted
    }
    flags {
      name
    }
    detailUrl {
      absoluteUrl
    }
    movie {
      genres {
        name
      }
    }
  }
}
